### ISSUE TITLE
shadcn cli is broken + some troubleshooting

### ISSUE THREAD

**Issue by dario24git** [Tokigin/astro-aceternity#2]
Following instruction i encountered some errors which may affect others so i decided to report them with fixes. I used npm and npx

## NPM folder

You may have found something like this trying to run `npx shadcn-ui@latest init`

`npm ERR! code ENOENT`
`npm ERR! syscall lstat`
`npm ERR! path C:\Users\user\AppData\Roaming\npm`
`npm ERR! errno -4058`
`npm ERR! enoent ENOENT: no such file or directory, lstat 'C:\Users\user\AppData\Roaming\npm'`
`npm ERR! enoent This is related to npm not being able to find a file.`
`npm ERR! enoent`

To fix this specific issue run

`New-Item -Path "$env:APPDATA\npm" -ItemType Directory
`
to create a npm folder where it is needed.

## shadcn, command not found

commands like:

`npx shadcn@latest init` or `npx shadcn-ui@latest add button` 

are causing a lot of problems in these months. The problem seems to be a bug in the latest version, so you have now 2 choices:

- `npm install shadcn` or `npm install -g shadcn`
`npx shadcn@latest init`
`npx shadcn@latest add button`
- Or you can just use 0.8.0v
`npx shadcn-ui@0.8.0 init`

## Others JSX integrations

At the beginning of by astro journey i had many problems with multiple jsx integrations in the same projects, so make sure solid and preact are not in your project or if you need them, follow [astro documentation](https://docs.astro.build/en/guides/integrations-guide/react/#combining-multiple-jsx-frameworks)

**Comment by Tokigin** [comment]
Sorry for the late and Thank you so much for noticing this issue. The cli is indeed causing problems lately. I will update the instruction and some modifications.
